# Graduação {#grad}

```{r fundo}
# define o fundo desta seção
fundo <- cores_anuario[2]
```

```{r}
# tabela 12 - Dados e características dos cursos de graduação oferecidos pela UnB
```

<br>

## Ingresso nos cursos de graduação pelo vestibular, PAS, ENEM e outras vias, por unidade acadêmica, curso e habilitação, UnB, 2019

```{r}
# tabela 13
Tabela2.03 <- rio::import("dados_graduacao/Tabela2.03.xlsx")


bind_cols("Unidade acadêmica / curso / habilitação" = Tabela2.03$`Unidade acadêmica / curso / habilitação`, 
                   map_df(Tabela2.03[-1], ~ format(.x, big.mark = "."))) %>% 
  tabela_geral(titulo = "Ingresso nos cursos de graduação pelo vestibular, PAS, ENEM e outras vias, por unidade acadêmica, curso e habilitação, UnB, 2019", 
               colunas = c("UNIDADE ACADÊMICA / CURSO / HABILITAÇÃO",
                           "1º SEM", "2º SEM",
                           "1º SEM", "2º SEM",
                           "1º SEM", "2º SEM",
                           "1º SEM", "2º SEM",
                           "1º SEM", "2º SEM",
                           "1º SEM", "2º SEM",
                           "1º SEM", "2º SEM",
                           "1º SEM", "2º SEM",
                           "TOTAL GERAL"),
               fundo = fundo,
               tamfonte = 12) %>% 
  colorir(dados = Tabela2.03) %>% 
  add_header_above(c("_\n", 
                     "VESTIBULAR" = 2,
                     "PAS" = 2,
                     "ENEM" = 2,
                     "TR.OB." = 2,
                     "TR.OPT." = 2,
                     "P.ESP." = 2,
                     "C.PEC" = 2,
                     "JUD." = 2,
                     "_\n"),
                   color = "white", extra_css = 'vertical-align: middle', background = fundo)
```

<br><br>

```{r}
# tabela 14
load("dados_graduacao/Tabela2.04.RData")
Tabela2.04 <- insere_descricao(Tabela2.04, "UNIDADE ACADÊMICA / CURSO / HABILITAÇÃO")

Tabela2.04 %>% 
  tabela_geral(
    titulo = "Ingresso de alunos e número de formados nos cursos de graduação, por unidade acadêmica, curso e habilitação, UnB, 2019",
    fundo = fundo,
    tamfonte = 14
  ) %>% 
  colorir(dados = Tabela2.04)
```

<br><br>

```{r}
# tabela 15
load("dados_graduacao/Tabela2.05.RData")
Tabela2.05 <- insere_descricao(Tabela2.05, "Faixa etária")

Tabela2.05 %>% 
  tabela_geral(
    titulo = "Ingresso de alunos nos cursos de graduação, por sexo e faixa etária, UnB, 2019",
    fundo = fundo
  )
```

<br><br>

```{r}
# tabela 16
load("dados_graduacao/Tabela2.06.RData")
```

<br><br>

```{r}
grad_formados <- rio::import("dados_graduacao/EvoFor.csv", header = TRUE)
grad_formados <- grad_formados %>% 
  modify_at(2:ncol(grad_formados), as.double) %>%
  filter(rowSums(is.na(.[, 2:ncol(grad_formados)])) != (ncol(grad_formados)-1)) %>%
  map_df(~replace_na(., 0))
```

```{r tab-grad-evo-for}
load("dados_graduacao/Tabela2.21.RData")

Tabela2.21 <- Tabela2.21 %>% 
  rownames_to_column(var = "Unidade acadêmica / curso / habilitação")

# tem que converter em excel...
# xfun::embed_file("dados_graduacao/EvoFor.csv")

Tabela2.21  %>% 
  tabela_geral("Evolução do número de ingressantes da UnB", negrito = TRUE, fundo = fundo) %>% 
  colorir(dados = Tabela2.21)
```

