# Produção Intelectual e Pesquisa {#pip}

```{r}
options(scipen = 9)
```

```{r}
prod_bibliografica <- rio::import("dados_producao_intelectual/producao_intelectual.xlsx", sheet=1)

prod_bibliografica %>% 
  map_df(~replace_na(., 0)) %>% 
  tabela_geral("Produção intelectual bibliográfica, 2019", linhatotal =TRUE, tamfonte = 14, fundo = "#303192") %>% 
  footnote(general = c("Extraído do Sistema Coleta da CAPES"),
           general_title = "Fonte:")
```

<br>

```{r}
prod_tecnica <- rio::import("dados_producao_intelectual/producao_intelectual.xlsx", sheet=2)

prod_tecnica %>% 
  map_df(~replace_na(., 0)) %>% 
  tabela_geral("Produção intelectual técnica, 2019", linhatotal =TRUE, tamfonte = 14, fundo = "#303192") %>% 
  footnote(general = c("Extraído do Sistema Coleta da CAPES"),
           general_title = "Fonte:")
```

<br>

```{r}
prod_artistica <- rio::import("dados_producao_intelectual/producao_intelectual.xlsx", sheet=3)

prod_artistica %>% 
  map_df(~replace_na(., 0)) %>% 
  tabela_geral("Produção intelectual artística, 2019", linhatotal =TRUE, tamfonte = 14, fundo = "#303192") %>% 
  footnote(general = c("Extraído do Sistema Coleta da CAPES"),
           general_title = "Fonte:")
```

<br>

```{r}
num_bolsa_pais <- rio::import("dados_producao_intelectual/producao_intelectual.xlsx", sheet=4)

num_bolsa_pais %>% 
  map_df(~replace_na(., 0)) %>% 
  tabela_geral("Número de bolsas e investimento em bolsas no país, por modalidade, 2019", 
               linhatotal =TRUE, tamfonte = 14, fundo = "#303192") %>% 
  footnote(number = c("Valor Mensal*"),
           general = c("DPG/DIRIC e Programas de Pós-Graduação, julho-2020"),
           general_title = "Fonte:")
```

<br>

```{r}
num_bolsa_ex <- rio::import("dados_producao_intelectual/producao_intelectual.xlsx", sheet=5)

num_bolsa_ex %>% 
  map_df(~replace_na(., 0)) %>% 
  tabela_geral("Número de bolsas e investimento em bolsas no exterior, por modalidade – UnB, 2019", 
               linhatotal =TRUE, tamfonte = 14, fundo = "#303192") %>% 
  footnote(number = c("Valor Mensal*","Cotação do dólar em 08/07/2020 = R$ 6,02"),
           general = c("Programas de Pós-Graduação, julho-2020."),
           general_title = "Fonte:")
```

<br>

```{r}
cnpq_grupos <- rio::import("dados_producao_intelectual/producao_intelectual.xlsx", sheet=6)

cnpq_grupos %>% 
  map_df(~replace_na(., 0)) %>% 
  tabela_geral("CNPq: Distribuição dos grupos de pesquisa por área de conhecimento cadastrados no diretório, 2019", 
               linhatotal =TRUE, tamfonte = 14, fundo = "#303192") %>% 
  footnote(general = c("DPG/ CNPq/ Plataforma Lattes (www.lattes.cnpq.br/web/dgp), julho-2020"),
           general_title = "Fonte:")
```

<br>

```{r}
unb_grupos <- rio::import("dados_producao_intelectual/producao_intelectual.xlsx", sheet=7)

unb_grupos %>% 
  map_df(~replace_na(., 0)) %>% 
  tabela_geral("Grupos de Pesquisa ativos da UnB, 2019", linhatotal =TRUE, tamfonte = 14, fundo = "#303192") %>% 
  footnote(general = c("DPI, julho-2020"),
           general_title = "Fonte:")
```

<br>

```{r}
pibic <- rio::import("dados_producao_intelectual/producao_intelectual.xlsx", sheet=8)

pibic %>% 
  map_df(~replace_na(., 0)) %>% 
  tabela_geral("Programa institucional de bolsas de iniciação científica – PIBIC, 2019", 
               linhatotal = FALSE, tamfonte = 14, fundo = "#303192") %>% 
  footnote(general = c("DPG/DIRIC, Julho-2020"),
           general_title = "Fonte:")
```

<br>

```{r}
bolsas_pibic <- rio::import("dados_producao_intelectual/producao_intelectual.xlsx", sheet=9)

bolsas_pibic %>% 
  map_df(~replace_na(., 0)) %>% 
  tabela_geral("Evolução do PIBIC na UnB, por inscrições, bolsas do CNPq e da UnB, 2015 a 2019", 
               linhatotal = FALSE, tamfonte = 14, fundo = "#303192") %>% 
  footnote(number = c("No último mês de 2015 houve a implementação das bolsas da FAP-DF*","Revisão da apuração do dado, julho-2020**","Em 2019, a FAPDF concedeu 352 bolsas de IC à UnB ***"),
           general = c("DPG/DIRIC, julho-2020"),
           general_title = "Fonte:")
```

<br>

```{r}
alunos_volunt <- rio::import("dados_producao_intelectual/producao_intelectual.xlsx", sheet=10)

alunos_volunt %>% 
  map_df(~replace_na(., 0)) %>% 
  tabela_geral("Evolução do número de alunos voluntários do PIBIC, 2015 a 2019", 
               linhatotal = FALSE, tamfonte = 14, fundo = "#303192") %>% 
  footnote(general = c("DPG/DIRIC, julho-2020"),
           general_title = "Fonte:")
```

<br>

```{r}
projetos_pibic <- rio::import("dados_producao_intelectual/producao_intelectual.xlsx", sheet=11)

projetos_pibic %>% 
  map_df(~replace_na(., 0)) %>% 
  tabela_geral("Evolução do número de projetos aprovados, orientadores e bolsistas do PIBIC, 2015 a 2019", 
               linhatotal = FALSE, tamfonte = 14, fundo = "#303192") %>% 
  footnote(number = c("Revisão da apuração do dado, julho-2020*","revisão da apuração do dado, julho-2020**"),
           general = c("DPG/DIRIC"),
           general_title = "Fonte:")
```

<br>

```{r}
trabalhos_pibic <- rio::import("dados_producao_intelectual/producao_intelectual.xlsx", sheet=12)

trabalhos_pibic %>% 
  map_df(~replace_na(., 0)) %>% 
  tabela_geral("Evolução do número de trabalhos apresentados pelos bolsistas do PIBIC nas reuniões da SBPC, 2015 a 2019", 
               linhatotal = FALSE, tamfonte = 14, fundo = "#303192") %>% 
  footnote(general = c("DPG/DIRIC, julho-2020"),
           general_title = "Fonte:")
```

<br>

```{r}
congresso_pibic <- rio::import("dados_producao_intelectual/producao_intelectual.xlsx", sheet=12)

congresso_pibic %>% 
  map_df(~replace_na(., 0)) %>% 
  tabela_geral("Evolução do número de trabalhos apresentados nos congressos do PIBIC – UnB, 2015 a 2019", 
               linhatotal = FALSE, tamfonte = 14, fundo = "#303192") %>% 
  footnote(general = c("DPG/DIRIC, julho-2020"),
           general_title = "Fonte:")
```
