# Planejamento, Execução Orçamentária e Convênios {#dpo}


```{r}
options(scipen = 9)
dpo <- rio::import("dados_planejamento/planejamento.xlsx", sheet=1)

```

```{r dpo}
#xfun::embed_file("")
dpo %>% 
  map_df(~replace_na(., 0)) %>% 
  tabela_geral("Orçamento da FUB – por grupos de despesas nas fontes Tesouro e Recursos Próprios (PLOA), 2019", linhatotal =  FALSE, tamfonte = 14, fundo = "#00AAAD") %>% footnote(general = c("LOA 2019 e OPI2019."),
           general_title = "Fonte:")
```

```{r}

dpa1<- rio::import("dados_planejamento/planejamento.xlsx", sheet=2)

```

```{r dpa1}
#xfun::embed_file("")
dpa1 %>% 
    tabela_geral("Instrumentos Assinados - Natureza, 2019", linhatotal = TRUE, tamfonte = 14, fundo = "#00AAAD") %>% footnote(general = c("DPA"),
           general_title = "Fonte:")
```

```{r}

dpa2<- rio::import("dados_planejamento/planejamento.xlsx", sheet=3)

```

```{r dpa2}
#xfun::embed_file("")
dpa2 %>% 
  map_df(~replace_na(., 0)) %>% 
  tabela_geral("Instrumentos Assinados - Esfera Administrativa, 2019", linhatotal =  FALSE, tamfonte = 14, fundo = "#00AAAD") %>% footnote(general = c("DPA"),
           general_title = "Fonte:")
```

```{r}

dpa3<- rio::import("dados_planejamento/planejamento.xlsx", sheet=4)

```

```{r dpa3}
#xfun::embed_file("")
dpa3 %>% 
  map_df(~replace_na(., 0)) %>% 
  tabela_geral("Instrumentos Assinados - Instrumento, 2019", linhatotal =  TRUE, tamfonte = 14, fundo = "#00AAAD") %>% footnote(general = c("DPA"),
           general_title = "Fonte:")
```

```{r}

dpa4<- rio::import("dados_planejamento/planejamento.xlsx", sheet=5)

```

```{r dpa4}
#xfun::embed_file("")
dpa4 %>% 
  map_df(~replace_na(., 0)) %>% 
  tabela_geral("Instrumentos Assinados (Nacionais e Internacionais), 2015 a 2019", linhatotal =  TRUE, tamfonte = 14, fundo = "#00AAAD") %>% footnote(general = c("DPA"),
           general_title = "Fonte:")
```